tasks:
  files:
    - file: tasks/t2i/gedit/gedit.py
      data_root: /share/project/mmdataset/t2i/GEdit-Bench
    # - file: tasks/t2i/gedit/gedit.py
    #   data_root: /share/project/mmdataset/t2i/GEdit-Bench
  debug: false
  try_run: false
  output_dir: outputs/Qwen-Image-Edit_Gen/
  num_workers: 4
  skip: false
  

model:
  model_name: Qwen-Image
  model_path: /share/project/models/vlm/Qwen-Image-Edit-2509
  processor_path: /share/project/models/vlm/Qwen2.5-VL-7B-Instruct
  exec: model_zoo/uni/qwen-image-edit/model_adapter.py
  port: 28000
  cuda_visible_devices: 0,1,2,3

extra_args:
  save_items: true
  batch_size: 1
  cfg_scale: 4.0
  resolution: 1024
  num_timesteps: 50
