tasks:
  files:
    - file: tasks/t2i/wise/wise.py
      data_root: /share/project/mmdataset/t2i/wise/
    # - file: tasks/t2i/gedit/gedit.py
    #   data_root: /share/project/mmdataset/t2i/GEdit-Bench
  debug: false
  try_run: false
  output_dir: outputs/Qwen-Image_Gen/
  num_workers: 4
  skip: false
  

model:
  model_name: Qwen-Image
  model_path: /share/project/models/vlm/Qwen-Image
  processor_path: /share/project/models/vlm/Qwen2.5-VL-7B-Instruct
  exec: model_zoo/uni/qwen-image/model_adapter.py
  port: 28012
  cuda_visible_devices: 4,5,6,7
  world_size: 1

extra_args:
  save_items: true
  batch_size: 1
  cfg_scale: 4.0
  resolution: 1024
  num_timesteps: 50